;WAP A 8085 ASSEMBLY LANGUAGE PROGRAM TO SUBTRACT THE CONTENT OF MEMORY LOCATION 2061H FROM THE THE CONTENT OF MEMORY LOCATION 2060H.STORE THE RESULE AT 2062H. IF THERE IS ANY BORROW STORE IT AT 2063H



